const CERTIFICATE_FACTORY_DEP = "CERTIFICATE_FACTORY";
const CERTIFICATE_REGISTRY_DEP = "CERTIFICATE_REGISTRY";

const CERTIFICATE_NAME = "CERTIFICATE";

module.exports = {
  CERTIFICATE_FACTORY_DEP: CERTIFICATE_FACTORY_DEP,
  CERTIFICATE_REGISTRY_DEP: CERTIFICATE_REGISTRY_DEP,
  CERTIFICATE_NAME: CERTIFICATE_NAME,
};
